services:

    dopiaza_slack_exception_logger.listener:
        class: Dopiaza\Slack\ExceptionLoggerBundle\Service\ExceptionHandler
        arguments:
            - "@logger"
            - "%kernel.environment%"
            - "@request_stack"
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
